//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 02:43:00 AM CEST 
//


package com.gamerevision.rusty.realityshard.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gamerevision.rusty.realityshard.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GameApp_QNAME = new QName("", "game-app");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gamerevision.rusty.realityshard.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GameApp }
     * 
     */
    public GameApp createGameApp() {
        return new GameApp();
    }

    /**
     * Create an instance of {@link ProtocolFilter }
     * 
     */
    public ProtocolFilter createProtocolFilter() {
        return new ProtocolFilter();
    }

    /**
     * Create an instance of {@link Shardlet }
     * 
     */
    public Shardlet createShardlet() {
        return new Shardlet();
    }

    /**
     * Create an instance of {@link Protocols }
     * 
     */
    public Protocols createProtocols() {
        return new Protocols();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Shardlets }
     * 
     */
    public Shardlets createShardlets() {
        return new Shardlets();
    }

    /**
     * Create an instance of {@link InitParam }
     * 
     */
    public InitParam createInitParam() {
        return new InitParam();
    }

    /**
     * Create an instance of {@link Protocol }
     * 
     */
    public Protocol createProtocol() {
        return new Protocol();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GameApp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game-app")
    public JAXBElement<GameApp> createGameApp(GameApp value) {
        return new JAXBElement<GameApp>(_GameApp_QNAME, GameApp.class, null, value);
    }

}
