//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 01:14:38 AM CEST 
//


package com.gamerevision.rusty.realityshard.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gamerevision.rusty.realityshard.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gamerevision.rusty.realityshard.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GameApp }
     * 
     */
    public GameApp createGameApp() {
        return new GameApp();
    }

    /**
     * Create an instance of {@link GameApp.Shardlets }
     * 
     */
    public GameApp.Shardlets createGameAppShardlets() {
        return new GameApp.Shardlets();
    }

    /**
     * Create an instance of {@link GameApp.Protocols }
     * 
     */
    public GameApp.Protocols createGameAppProtocols() {
        return new GameApp.Protocols();
    }

    /**
     * Create an instance of {@link GameApp.Protocols.Protocol }
     * 
     */
    public GameApp.Protocols.Protocol createGameAppProtocolsProtocol() {
        return new GameApp.Protocols.Protocol();
    }

    /**
     * Create an instance of {@link InitParam }
     * 
     */
    public InitParam createInitParam() {
        return new InitParam();
    }

    /**
     * Create an instance of {@link GameApp.Info }
     * 
     */
    public GameApp.Info createGameAppInfo() {
        return new GameApp.Info();
    }

    /**
     * Create an instance of {@link GameApp.Context }
     * 
     */
    public GameApp.Context createGameAppContext() {
        return new GameApp.Context();
    }

    /**
     * Create an instance of {@link GameApp.Shardlets.Shardlet }
     * 
     */
    public GameApp.Shardlets.Shardlet createGameAppShardletsShardlet() {
        return new GameApp.Shardlets.Shardlet();
    }

    /**
     * Create an instance of {@link GameApp.Protocols.Protocol.ProtocolFilter }
     * 
     */
    public GameApp.Protocols.Protocol.ProtocolFilter createGameAppProtocolsProtocolProtocolFilter() {
        return new GameApp.Protocols.Protocol.ProtocolFilter();
    }

}
